Revert "Compile with log"
Introduces error when ```cargo build```-ing in ```examples/rp```:
```
error: unknown display hint: "x?"
  --> /home/user/d/embassy/embassy-usb/src/host/mod.rs:67:16
   |
67 |         trace!("Descriptor {}: {:x?}", core::any::type_name::<T>(), buf);
   |                ^^^^^^^^^^^^^^^^^^^^^^
```

This reverts commit 455c2c708bda0dbc6dc48b6fab95e6c0a194245b.