Fix STM32 SPI examples
In their current state, these examples fail with:

     ERROR panicked at /home/phoracek/.cargo/git/checkouts/embassy-9312dcb0ed774b29/5f8f867/embassy-stm32/src/spi/mod.rs:769:9:
     assertion `left == right` failed
       left: 128
      right: 20

It is due to `String::as_bytes` returning slice shrinked to the occupied
size of the string.

With this change, these examples are aligned with the BDMA example,
using read and write buffers.

Signed-off-by: Petr Horacek <petr@zlosynth.com>